# Generated by Django 3.2.8 on 2021-10-18 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year',
        ),
        migrations.AddField(
            model_name='students',
            name='f_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='First_Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='l_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Second_Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('ce', 'CE'), ('eee', 'EEE'), ('mech', 'MECH'), ('cse', 'CSE'), ('it', 'IT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=255, verbose_name='Gender'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='SessionYearModel',
        ),
    ]
